---
- name: Config Apache Web Server
  hosts: all
  become: yes
  vars:
    user_name: ravi
    custom_http_port: 80

  tasks:
  - name: Copy config to centos httpd
    template:
      src: httpd.j2
      dest: /etc/httpd/conf/httpd.conf
    when: ansible_distribution == "CentOS" 
    notify:
    - Restart HTTPD

  - name: Set Permissive For HTTPD
    selinux:
      policy: targeted
      state: permissive
    when: ansible_distribution == "CentOS" 


  - name: Copy config to ubuntu apache2
    template:
      src: ports.j2
      dest: /etc/apache2/ports.conf
    when: ansible_distribution == "Ubuntu" 
    notify:
    - Restart APACHE2

  - name: Copy Date App
    copy:
      src: date.php
      dest: /var/www/html/date.php
    when: ansible_distribution == "CentOS" 

  - name: Install PHP
    yum:
      name: php
      state: present
    when: ansible_distribution == "CentOS" 
    notify:
    - Restart HTTPD

  handlers:

  - name: Restart APACHE2
    service:
      name: apache2
      state: restarted
    when: ansible_distribution == "Ubuntu" 

  - name: Restart HTTPD
    service:
      name: httpd
      state: restarted
    when: ansible_distribution == "CentOS" 



...

