---
  - name: Install PHP
    yum:
      name: php
      state: present
    when: ansible_distribution == "CentOS" or ansible_distribution == "Amazon"
    notify:
    - Restart HTTPD


  - name: Install PHP
    apt:
      name: php
      state: present
    when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"
    notify:
    - Restart APACHE2

...
